#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-echoe
Version  : 4.6.6
Release  : 5
URL      : https://rubygems.org/downloads/echoe-4.6.6.gem
Source0  : https://rubygems.org/downloads/echoe-4.6.6.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : AFL-3.0 MIT
BuildRequires : ruby
BuildRequires : rubygem-allison
BuildRequires : rubygem-echoe
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rubyforge

%description
Echoe
A Rubygems packaging tool that provides Rake tasks for documentation, extension compiling, testing, and deployment.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n echoe-4.6.6
gem spec %{SOURCE0} -l --ruby > rubygem-echoe.gemspec

%build
gem build rubygem-echoe.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
echoe-4.6.6.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/echoe-4.6.6.gem
/usr/lib64/ruby/gems/2.3.0/gems/echoe-4.6.6/CHANGELOG
/usr/lib64/ruby/gems/2.3.0/gems/echoe-4.6.6/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/echoe-4.6.6/MIT-LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/echoe-4.6.6/Manifest
/usr/lib64/ruby/gems/2.3.0/gems/echoe-4.6.6/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/echoe-4.6.6/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/echoe-4.6.6/echoe.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/echoe-4.6.6/echoe.pem
/usr/lib64/ruby/gems/2.3.0/gems/echoe-4.6.6/lib/echoe.rb
/usr/lib64/ruby/gems/2.3.0/gems/echoe-4.6.6/lib/echoe/extensions.rb
/usr/lib64/ruby/gems/2.3.0/gems/echoe-4.6.6/lib/echoe/platform.rb
/usr/lib64/ruby/gems/2.3.0/gems/echoe-4.6.6/lib/echoe/rubygems.rb
/usr/lib64/ruby/gems/2.3.0/gems/echoe-4.6.6/vendor/rake/MIT-LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/echoe-4.6.6/vendor/rake/lib/rake/contrib/compositepublisher.rb
/usr/lib64/ruby/gems/2.3.0/gems/echoe-4.6.6/vendor/rake/lib/rake/contrib/ftptools.rb
/usr/lib64/ruby/gems/2.3.0/gems/echoe-4.6.6/vendor/rake/lib/rake/contrib/publisher.rb
/usr/lib64/ruby/gems/2.3.0/gems/echoe-4.6.6/vendor/rake/lib/rake/contrib/rubyforgepublisher.rb
/usr/lib64/ruby/gems/2.3.0/gems/echoe-4.6.6/vendor/rake/lib/rake/contrib/sshpublisher.rb
/usr/lib64/ruby/gems/2.3.0/gems/echoe-4.6.6/vendor/rake/lib/rake/contrib/sys.rb
/usr/lib64/ruby/gems/2.3.0/specifications/echoe-4.6.6.gemspec
