#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-echoe
Version  : 4.6.6
Release  : 4
URL      : https://rubygems.org/downloads/echoe-4.6.6.gem
Source0  : https://rubygems.org/downloads/echoe-4.6.6.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : AFL-3.0 MIT
BuildRequires : ruby
BuildRequires : rubygem-allison
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rubyforge

%description
Echoe
A Rubygems packaging tool that provides Rake tasks for documentation, extension compiling, testing, and deployment.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n echoe-4.6.6
gem spec %{SOURCE0} -l --ruby > rubygem-echoe.gemspec

%build
gem build rubygem-echoe.gemspec

%install
gem_dir=$(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .${gem_dir} \
--bindir .%{_bindir} \
echoe-4.6.6.gem

mkdir -p %{buildroot}${gem_dir}
cp -pa .${gem_dir}/* \
%{buildroot}${gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/echoe-4.6.6.gem
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/Platform/cdesc-Platform.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/Platform/gcc%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/Platform/java%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/Platform/make-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/Platform/msvc%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/Platform/rake-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/Platform/suffix-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/Platform/windows%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/apply_pattern-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/author-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/bin_files-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/cdesc-Echoe.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/certificate_chain-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/changelog-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/changelog_patterns-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/changes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/clean_pattern-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/define_tasks-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/dependencies-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/description-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/development_dependencies-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/docs_host-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/email-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/eval-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/executable_pattern-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/extension_pattern-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/extensions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/extra_deps-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/files-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/gem_bin-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/gemspec_format-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/gemspec_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/honor_gitignore%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/ignore_pattern-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/include_gemspec-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/include_rakefile-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/install_message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/lib_files-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/licenses-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/manifest_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/need_gem-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/need_tar_gz-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/need_tgz-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/need_zip-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/platform-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/private_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/project-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/rakefile_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/rcov_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/rdoc_files-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/rdoc_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/rdoc_pattern-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/rdoc_template-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/require_paths-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/require_signed-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/retain_gemspec-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/ruby_version-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/rubygems_version-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/runtime_dependencies-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/silence-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/spec-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/spec_pattern-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/summary-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/test_files-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/test_pattern-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/use_sudo-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Echoe/version-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Gem/Specification/cdesc-Specification.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Gem/Specification/old_validate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Gem/Specification/validate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Gem/cdesc-Gem.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Rake/SshDirPublisher/cdesc-SshDirPublisher.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Rake/Task/cdesc-Task.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Rake/TaskManager/cdesc-TaskManager.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/Rake/cdesc-Rake.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/String/cdesc-String.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/page-CHANGELOG.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/page-LICENSE.ri
/usr/lib64/ruby/gems/2.2.0/doc/echoe-4.6.6/ri/page-README_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/gems/echoe-4.6.6/CHANGELOG
/usr/lib64/ruby/gems/2.2.0/gems/echoe-4.6.6/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/echoe-4.6.6/MIT-LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/echoe-4.6.6/Manifest
/usr/lib64/ruby/gems/2.2.0/gems/echoe-4.6.6/README.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/echoe-4.6.6/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/echoe-4.6.6/echoe.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/echoe-4.6.6/echoe.pem
/usr/lib64/ruby/gems/2.2.0/gems/echoe-4.6.6/lib/echoe.rb
/usr/lib64/ruby/gems/2.2.0/gems/echoe-4.6.6/lib/echoe/extensions.rb
/usr/lib64/ruby/gems/2.2.0/gems/echoe-4.6.6/lib/echoe/platform.rb
/usr/lib64/ruby/gems/2.2.0/gems/echoe-4.6.6/lib/echoe/rubygems.rb
/usr/lib64/ruby/gems/2.2.0/gems/echoe-4.6.6/vendor/rake/MIT-LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/echoe-4.6.6/vendor/rake/lib/rake/contrib/compositepublisher.rb
/usr/lib64/ruby/gems/2.2.0/gems/echoe-4.6.6/vendor/rake/lib/rake/contrib/ftptools.rb
/usr/lib64/ruby/gems/2.2.0/gems/echoe-4.6.6/vendor/rake/lib/rake/contrib/publisher.rb
/usr/lib64/ruby/gems/2.2.0/gems/echoe-4.6.6/vendor/rake/lib/rake/contrib/rubyforgepublisher.rb
/usr/lib64/ruby/gems/2.2.0/gems/echoe-4.6.6/vendor/rake/lib/rake/contrib/sshpublisher.rb
/usr/lib64/ruby/gems/2.2.0/gems/echoe-4.6.6/vendor/rake/lib/rake/contrib/sys.rb
/usr/lib64/ruby/gems/2.2.0/specifications/echoe-4.6.6.gemspec
